apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: express-sample-app
    - name: source-repo
      value: "https://github.com/cloud-native-garage-method-cohort/dennis-app.git"
    - name: image-repo
      value: quay.io/dennis_steenbergen/express_sample_app
  pipelineRef:
    name: express
  workspaces: 
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce