apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/dennis_steenbergen/express_sample_app
commonLabels:
  app.kubernetes.io/instance: express-sample-app
  app.kubernetes.io/name: express-sample-app
kind: Deployment
metadata:
  labels:
    app.openshift.io/runtime: js
  name: express-sample-app
spec: